#service postgresql stop, start, restart
#sudo -u postgres psql //to access postgres shell
common: &common
  adapter: postgresql
  username: user
  password: password 

development:
  <<: *common
  database: railstutorial_development

test: &test
  <<: *common
  database: railstutorial_test

production:
  <<: *common
  database: railstutorial_production
cucumber:
  <<: *test